### ISSUE TITLE
Comments at line endings not recognized

### ISSUE THREAD

**Issue by tabulon** [caleb531/language-pip#1]
Hello,

Thank you for having made this. Though it may seem minor to some, I really enjoy syntax highlighting which helps spot errors, which imho is useful even on simple file formats like `requirements.txt`.

On current master branch, there appears to be a small bug for the pip requirements grammer , which prevents it from recognizing **_trailing_ line comments**.

Here's an example (observe the line that contains `NOK`):

```
# OK. A full line comment is recognized as such `language-pip`
   #   OK. Another full line comment with preceding whitespace (also recognized)

six
pytest  # NOK. A TRAILING line comment is NOT duely recognized by `language-pip`


# Naturally, it's good that the '#' below (not preceded by whitespace)
# does not signal the start of a comment !
[-e] git://git.example.com/MyProject#egg=MyProject

```
----

Below is an excerpt from the [pip docmentation](https://pip.pypa.io/en/latest/reference/pip_install/#requirements-file-format) relating to the format of 'requirements' files:

> A line that begins with # is treated as a comment and ignored.
> Whitespace followed by a # causes the # and the remainder of the line to be treated as a comment.

----
I have put together a tiny pull request that fixes the regular expression, which I will submit shortly. Please consider merging it, or otherwise let me know if you see any issues with it.

As a bonus, there is a second pull request that adds an `examples` directory with a basic requirements file that demonstrates the issue as well as a couple other files that contain requirements file syntax examples from pip documentation.

If you wish, feel free to merge that one as well, since it helps visually inspecting/testing the grammer as one works on it.

Thanks again!
Cheers,
Tabulo[n]

**Comment by caleb531** [comment]
Thanks, @tabulon. I've merged in your second PR now, but obviously haven't had a chance to push a new release yet. I'll see if I have time to do so tonight.

**Comment by caleb531** [comment]
@tabulon I've just pushed out v2.0.1 containing all of your proposed changes. Please let me know if everything is to your satisfaction, and create a new issue if anything arises.

**Comment by tabulon** [comment]
Thank you for your reactivity @caleb531. 
I was able install `v2.0.1` via `atom`, and it works as expected. 
Thanks again!
